replicaCount: 1

image:
  repository: "<your-ecr-repo-url>" # This will be set dynamically during deployment
  tag: "{{ .Values.image.tag }}"  
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}
