name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}
      
    - name: Build Docker Image
      run: docker build -t ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA .

    - name: Push Docker Image
      run: docker push ${{ secrets.ECR_REPOSITORY }}:$GITHUB_SHA

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: v1.20.0

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Deploy with Helm
      run: |
        helm upgrade --install sample-app ./helm --set image.repository=${{ secrets.ECR_REPOSITORY }} --set image.tag=$GITHUB_SHA
        helm upgrade --install prometheus prometheus-community/prometheus --namespace default
        helm upgrade --install grafana grafana/grafana --namespace default
